"""Immutable records describing what an agent run cost and how long it took.

Three types, in increasing order of scope:

* :class:`TokenUsage` -- the token counts for a single model call.
* :class:`TraceStep` -- one graph node's execution: timing, tokens, cost.
* :class:`Trace` -- a whole agent run, holding its steps and their totals.

All three are frozen dataclasses with ``to_dict()`` / ``from_dict()``, so a
trace survives a round trip through JSON without losing precision or gaining a
dependency on this package. That matters because traces are written to disk by
:mod:`wardhook.observability.store` and read back by tooling that may not have
Wardhook installed at all.

**On the two clocks.** ``started_at`` is a wall-clock ISO-8601 timestamp,
because a persisted trace is only useful if you can line it up against your
application logs. ``latency_ms`` is measured with :func:`time.perf_counter`,
which is monotonic and therefore immune to NTP adjustments and daylight-saving
transitions -- subtracting two wall-clock readings can legitimately produce a
negative duration, and a negative latency in a dashboard is worse than useless.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field, replace
from typing import Any

__all__ = ["TokenUsage", "Trace", "TraceStep"]


@dataclass(frozen=True, slots=True)
class TokenUsage:
    """Token counts for one or more model calls.

    Field names mirror LangChain's ``usage_metadata`` so the mapping between
    the two is obvious at a glance.

    .. warning::
       Following LangChain's convention, :attr:`input_tokens` is the **total**
       number of input tokens, cache reads and cache writes included -- it is
       not the uncached remainder. :attr:`uncached_input_tokens` gives that.
       Getting this backwards double-counts cached tokens and inflates every
       cost estimate, which is why :mod:`wardhook.observability.pricing` bills
       from the derived value rather than from ``input_tokens`` directly.

    Attributes:
        input_tokens: Total input tokens, including cached ones.
        output_tokens: Tokens generated by the model.
        cache_read_tokens: Input tokens served from a prompt cache.
        cache_write_tokens: Input tokens written into a prompt cache.
        reasoning_tokens: Output tokens spent on extended thinking. Counted
            within ``output_tokens``, not in addition to it.

    Example:
        >>> a = TokenUsage(input_tokens=100, output_tokens=20)
        >>> b = TokenUsage(input_tokens=50, output_tokens=5)
        >>> (a + b).total_tokens
        175
    """

    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_tokens: int = 0
    cache_write_tokens: int = 0
    reasoning_tokens: int = 0

    @property
    def total_tokens(self) -> int:
        """Input plus output tokens."""
        return self.input_tokens + self.output_tokens

    @property
    def uncached_input_tokens(self) -> int:
        """Input tokens billed at the full rate.

        Returns:
            ``input_tokens`` less anything that was read from or written to a
            prompt cache, floored at zero so a provider reporting inconsistent
            counts cannot produce a negative charge.
        """
        return max(0, self.input_tokens - self.cache_read_tokens - self.cache_write_tokens)

    @property
    def is_empty(self) -> bool:
        """Whether no tokens were recorded at all."""
        return self.total_tokens == 0

    def __add__(self, other: TokenUsage) -> TokenUsage:
        """Add two usages field by field.

        Args:
            other: The usage to add.

        Returns:
            A new :class:`TokenUsage` holding the sums.
        """
        if not isinstance(other, TokenUsage):
            return NotImplemented
        return TokenUsage(
            input_tokens=self.input_tokens + other.input_tokens,
            output_tokens=self.output_tokens + other.output_tokens,
            cache_read_tokens=self.cache_read_tokens + other.cache_read_tokens,
            cache_write_tokens=self.cache_write_tokens + other.cache_write_tokens,
            reasoning_tokens=self.reasoning_tokens + other.reasoning_tokens,
        )

    def to_dict(self) -> dict[str, int]:
        """Return a JSON-serialisable record, omitting zero-valued fields.

        Returns:
            A dict of the non-zero counts. Zeros are dropped because most calls
            use no cache and no thinking, and a trace file full of ``"audio":
            0`` is harder to read for no benefit.
        """
        record = {
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
            "cache_read_tokens": self.cache_read_tokens,
            "cache_write_tokens": self.cache_write_tokens,
            "reasoning_tokens": self.reasoning_tokens,
        }
        return {key: value for key, value in record.items() if value}

    @classmethod
    def from_dict(cls, data: Mapping[str, Any] | None) -> TokenUsage:
        """Rebuild a usage from :meth:`to_dict` output.

        Args:
            data: A mapping of token counts, or ``None`` for an empty usage.
                Unknown keys are ignored, so a trace written by a newer version
                still loads.

        Returns:
            The reconstructed usage.

        Example:
            >>> TokenUsage.from_dict({"input_tokens": 10}).input_tokens
            10
        """
        data = data or {}
        return cls(
            input_tokens=int(data.get("input_tokens", 0)),
            output_tokens=int(data.get("output_tokens", 0)),
            cache_read_tokens=int(data.get("cache_read_tokens", 0)),
            cache_write_tokens=int(data.get("cache_write_tokens", 0)),
            reasoning_tokens=int(data.get("reasoning_tokens", 0)),
        )


@dataclass(frozen=True, slots=True)
class TraceStep:
    """One graph node's execution.

    Attributes:
        node: Name of the graph node, such as ``"call_model"``.
        run_id: Identifier of the run this step belongs to.
        started_at: Wall-clock ISO-8601 timestamp of when the node began.
        latency_ms: Wall time spent in the node, from a monotonic clock.
        usage: Tokens consumed by model calls made inside this node. Nodes that
            never call a model -- retrieval, guardrails -- carry an empty usage.
        cost: Estimated cost in US dollars. Zero for an unpriced model; see
            :mod:`wardhook.observability.pricing`.
        model: The model invoked, if any.
        error: Description of the exception that ended the node, if it failed.

    Example:
        >>> step = TraceStep(
        ...     "call_model",
        ...     "r1",
        ...     "2026-06-24T10:00:00Z",
        ...     412.5,
        ...     TokenUsage(input_tokens=900, output_tokens=120),
        ... )
        >>> step.tokens_out, step.failed
        (120, False)
    """

    node: str
    run_id: str
    started_at: str
    latency_ms: float
    usage: TokenUsage = field(default_factory=TokenUsage)
    cost: float = 0.0
    model: str | None = None
    error: str | None = None

    @property
    def tokens_in(self) -> int:
        """Total input tokens consumed by this node."""
        return self.usage.input_tokens

    @property
    def tokens_out(self) -> int:
        """Tokens generated by this node."""
        return self.usage.output_tokens

    @property
    def failed(self) -> bool:
        """Whether the node raised."""
        return self.error is not None

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable record of this step.

        Returns:
            A dict with the node name, timing, usage, cost, and -- only when
            set -- the model and error.
        """
        record: dict[str, Any] = {
            "node": self.node,
            "run_id": self.run_id,
            "started_at": self.started_at,
            "latency_ms": round(self.latency_ms, 3),
            "usage": self.usage.to_dict(),
            "cost": round(self.cost, 8),
        }
        if self.model is not None:
            record["model"] = self.model
        if self.error is not None:
            record["error"] = self.error
        return record

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> TraceStep:
        """Rebuild a step from :meth:`to_dict` output.

        Args:
            data: The serialised step.

        Returns:
            The reconstructed step.
        """
        return cls(
            node=str(data["node"]),
            run_id=str(data.get("run_id", "")),
            started_at=str(data.get("started_at", "")),
            latency_ms=float(data.get("latency_ms", 0.0)),
            usage=TokenUsage.from_dict(data.get("usage")),
            cost=float(data.get("cost", 0.0)),
            model=data.get("model"),
            error=data.get("error"),
        )


@dataclass(frozen=True, slots=True)
class Trace:
    """A complete agent run and every node it executed.

    Attributes:
        run_id: Identifier of the run, matching the one the agent reported.
        steps: The nodes executed, in the order they started.
        started_at: Wall-clock ISO-8601 timestamp of when the run began.
        latency_ms: Total wall time for the run. This is measured around the
            whole invocation, so it is normally *greater* than the sum of the
            steps -- the difference is LangGraph's own routing overhead.
        metadata: Free-form context supplied by the caller, typically the agent
            name and the model.
        error: Description of the exception that ended the run, if it failed.

    Example:
        >>> step = TraceStep(
        ...     "call_model",
        ...     "r1",
        ...     "2026-06-24T10:00:00Z",
        ...     400.0,
        ...     TokenUsage(input_tokens=900, output_tokens=120),
        ...     cost=0.007,
        ... )
        >>> trace = Trace("r1", (step,), "2026-06-24T10:00:00Z", 415.0)
        >>> trace.total_tokens_out, round(trace.total_cost, 4)
        (120, 0.007)
    """

    run_id: str
    steps: tuple[TraceStep, ...] = ()
    started_at: str = ""
    latency_ms: float = 0.0
    metadata: Mapping[str, Any] = field(default_factory=dict)
    error: str | None = None

    @property
    def total_usage(self) -> TokenUsage:
        """Token usage summed across every step."""
        total = TokenUsage()
        for step in self.steps:
            total = total + step.usage
        return total

    @property
    def total_cost(self) -> float:
        """Estimated cost of the whole run, in US dollars."""
        return sum(step.cost for step in self.steps)

    @property
    def total_tokens_in(self) -> int:
        """Input tokens across every step."""
        return self.total_usage.input_tokens

    @property
    def total_tokens_out(self) -> int:
        """Output tokens across every step."""
        return self.total_usage.output_tokens

    @property
    def failed(self) -> bool:
        """Whether the run itself failed, or any node within it did."""
        return self.error is not None or any(step.failed for step in self.steps)

    @property
    def slowest_step(self) -> TraceStep | None:
        """The node that took longest, or ``None`` for an empty trace."""
        return max(self.steps, key=lambda step: step.latency_ms, default=None)

    def with_steps(self, steps: Iterable[TraceStep]) -> Trace:
        """Return a copy of this trace carrying different steps.

        Args:
            steps: The replacement steps.

        Returns:
            A new trace; this one is unchanged.
        """
        return replace(self, steps=tuple(steps))

    def to_dict(self) -> dict[str, Any]:
        """Return a JSON-serialisable record of the whole run.

        Returns:
            A dict with the run id, timing, totals, every step, and -- only
            when set -- the metadata and error.
        """
        record: dict[str, Any] = {
            "run_id": self.run_id,
            "started_at": self.started_at,
            "latency_ms": round(self.latency_ms, 3),
            "steps": [step.to_dict() for step in self.steps],
            "totals": {
                "usage": self.total_usage.to_dict(),
                "cost": round(self.total_cost, 8),
                "steps": len(self.steps),
            },
        }
        if self.metadata:
            record["metadata"] = dict(self.metadata)
        if self.error is not None:
            record["error"] = self.error
        return record

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Trace:
        """Rebuild a trace from :meth:`to_dict` output.

        The ``totals`` block is deliberately *not* read back: it is derived
        data, and recomputing it from the steps means a hand-edited or
        truncated trace file cannot claim totals its steps do not support.

        Args:
            data: The serialised trace.

        Returns:
            The reconstructed trace.
        """
        return cls(
            run_id=str(data.get("run_id", "")),
            steps=tuple(TraceStep.from_dict(step) for step in data.get("steps", ())),
            started_at=str(data.get("started_at", "")),
            latency_ms=float(data.get("latency_ms", 0.0)),
            metadata=dict(data.get("metadata", {})),
            error=data.get("error"),
        )
